version: "3"

services:

  runtime-setup:
    image: prometheus:22.04-5.7
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.7"

  documentation-check:
    image: prometheus:22.04-5.7

  test:
    image: prometheus:22.04-5.7
    environment: []
      #- SANITIZER_ARG=--sanitize=thread

  update-benchmark-baseline:
    image: prometheus:22.04-5.7
    environment:
      - SWIFT_VERSION=5.7

  shell:
    image: prometheus:22.04-5.7
