# this file is not designed to be run directly
# instead, use the docker-compose.<os>.<swift> files
# eg docker-compose -f docker/docker-compose.yaml -f docker/docker-compose.2204.57.yaml run test
version: "3"

services:

  runtime-setup:
    image: prometheus:default
    build:
      context: .
      dockerfile: Dockerfile

  common: &common
    image: prometheus:default
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh
      - ..:/swift-prometheus:z
    working_dir: /swift-prometheus
    cap_drop:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE

  soundness:
    <<: *common
    command: /bin/bash -xcl "./scripts/soundness.sh"

  documentation-check:
    <<: *common
    command: /bin/bash -xcl "./scripts/check-docs.sh"

  test:
    <<: *common
    depends_on: [runtime-setup]
    command: /bin/bash -xcl "swift test -Xswiftc -warnings-as-errors --enable-test-discovery $${SANITIZER_ARG-} $${IMPORT_CHECK_ARG-} && cd Benchmarks && swift package benchmark baseline check --check-absolute-path Thresholds/$${SWIFT_VERSION-}/"

  update-benchmark-baseline:
    <<: *common
    command: /bin/bash -xcl "cd Benchmarks && swift package --disable-sandbox --scratch-path .build/$${SWIFT_VERSION-}/ --allow-writing-to-package-directory benchmark --format metricP90AbsoluteThresholds --path Thresholds/$${SWIFT_VERSION-}/"

  # util

  shell:
    <<: *common
    entrypoint: /bin/bash
