name: tests
on: { pull_request: {} }

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swiftver:
          - swift:5.2
          - swift:5.3
          - swift:5.4
          - swift:5.5
          - swift:5.6
          - swift:5.7
          - swiftlang/swift:nightly-main
        swiftos:
          - focal
    container: ${{ format('{0}-{1}', matrix.swiftver, matrix.swiftos) }}
    steps:
      - name: Check out SwiftPrometheus
        uses: actions/checkout@v2
      - name: Run tests with Thread Sanitizer
        timeout-minutes: 30
        env:
          CI_RUN: 'TRUE'
        run: swift test --enable-test-discovery --sanitize=thread
  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: ['latest', 'latest-stable']
    steps:
      - name: Select toolchain
        uses: maxim-lobanov/setup-xcode@v1.2.1
        with:
          xcode-version: ${{ matrix.toolchain }}
      - name: Check out SwiftPrometheus
        uses: actions/checkout@v2
      - name: Run tests with Thread Sanitizer
        timeout-minutes: 30
        env:
          CI_RUN: 'TRUE'
        run: swift test --enable-test-discovery --sanitize=thread
